In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
print(a.ndim)

1


In [4]:
b=np.array([[1,2,3],[4,5,6]])

In [14]:
print(b.ndim)

2


In [15]:
c = np.array([[[1,2],[3,4],[5,6],[7,6]]])

In [16]:
print(c.ndim)

3


In [17]:
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 6]]]


In [18]:
print(a.shape)

(4,)


In [19]:
print(b.shape)

(2, 3)


In [20]:
print(c.shape)

(1, 4, 2)


## Functions for creating array

In [21]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


## Using linspace

In [23]:
a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [24]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [28]:
print(np.diag(a))

[1 2 3 4]


## Basic Data Types

In [29]:
a = np.arange(10)
print(a.dtype)

int64


In [30]:
a = np.arange(10,dtype="float64")
print(a.dtype)

float64


In [31]:
a = np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


## Other Data types

In [32]:
a = np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [33]:
a = np.array([True,False])
print(a.dtype)

bool


In [34]:
a = np.array(['Satya','Vamsi'])
print(a.dtype) 

<U5


## Indexing and Slicing

In [35]:
a = np.arange(10)
print(a[5])

5


In [36]:
a = np.diag([1,2,3])
print(a[2,2])

3


## Slicing

In [37]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
print(a[1:8:2])

[1 3 5 7]


In [39]:
a = np.arange(10)
a[5: ]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

## Copies and Slicing

In [40]:
import numpy as np

In [41]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [42]:
print(np.shares_memory(a,b))

True


In [43]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [44]:
a = np.arange(10)
b = a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [45]:
print(np.shares_memory(a,b))

False


In [46]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


## Random Generator

In [47]:
a = np.random.randint(0,20,15)
print(a)

[ 7  8  8 10  0  4 18  1  0 17  5  3 16  8 16]


In [48]:
mask=(a%2==0)

In [49]:
mask_a = a[mask]
print(mask_a)

[ 8  8 10  0  4 18  0 16  8 16]


In [50]:
a[mask] = -1
print(a)

[ 7 -1 -1 -1 -1 -1 -1  1 -1 17  5  3 -1 -1 -1]


## Element wise operation

## 1.Basic operation

In [51]:
a = np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [52]:
print(a**2)

[ 1  4  9 16]


## 
All arithmetic operates elements wise

In [53]:
b = np.ones(4) + 1
print("a = ",a)
print("b = ",b)

a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [54]:
print(a*b)

[2. 4. 6. 8.]


In [55]:

print(a+b)

[3. 4. 5. 6.]


In [56]:
c = np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [57]:
print(c*c)
print("************************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
************************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## Comparison Operators

In [58]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [59]:
print(np.array_equal(a,c))

True


## Logical Operators

In [60]:
a = np.array([1,0,1,0],dtype = "bool")
b = np.array([1,1,0,0],dtype = "bool")

In [61]:
print(np.logical_or(a,b))

[ True  True  True False]


In [62]:
print(np.logical_and(a,b))

[ True False False False]


## Trigonometry/Transcendental Function

In [63]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [64]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [66]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [67]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
